version: "3.7"
services:
    php8:
        container_name: secret-santa
        build: docker/php8
        ports:
            - "9000:8000"
        volumes:
            - ./project:/var/www/html/secret-santa
        depends_on:
            - mysql
            - phpmyadmin

    mailer:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    mysql:
        image: mariadb:${MARIADB_VERSION:-latest}
        container_name: data_mysql
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=password
        restart: always

    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:${PHPMYADMIN_VERSION:-latest}
        container_name: data_phpmyadmin
        restart: always
        ports:
            - 9080:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password

volumes:
    mysql:
